sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: sa123456
  cos:
    rootSrc: https://takeout-1316786888.cos.ap-nanjing.myqcloud.com
    bucketAddr: ap-nanjing
    SecretId: AKID8C6mGZTAF8rPjphLo6B4wd6A3lGXZR6Y
    SecretKey: HU0NkrobBXgfS0LYaOyJUM0PbcOwGQNH
    bucketName: takeout-1316786888
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxe9b2017582aba0d2
    secret: 32c3f7feeb85465a0ba2fae85f927ea4

#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\pay\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl:  https://1ad32bb9.r18.cpolar.top/notify/paySuccess
#    refundNotifyUrl: https://1ad32bb9.r18.cpolar.top/notify/refundSuccess