sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPznhCzK44ZY64kQ7Sf
    access-key-secret: T6vmFwmgddHkpxZr24AtDTy0GSKyzu
    bucket-name: sky-take-out-stringzhua